items:
  - itemId: "item_1"
    itemName: "Apple"
    itemCategory: "F_N_V"
  - itemId: "item_2"
    itemName: "Onion"
    itemCategory: "F_N_V"
  - itemId: "item_3"
    itemName: "Milk"
    itemCategory: "DAIRY"

warehouseConfig:
  "warehouse_1":
    - date: "01-01-2020"
      itemQuantityMap:
        item_1: 100
        item_2: 100
        item_3: 100
    - date: "02-01-2020"
      itemQuantityMap:
        item_1: 100
        item_2: 200
    - date: "03-01-2020"
      itemQuantityMap:
        item_2: 100
        item_3: 200

categoryThresholdConfig:
  - date: "01-01-2020"
    itemCategoryThresholdMap:
      F_N_V: 50
      DAIRY: 20
  - date: "02-01-2020"
    itemCategoryThresholdMap:
      F_N_V: 50
      DAIRY: 20
  - date: "03-01-2020"
    itemCategoryThresholdMap:
      F_N_V: 50
      DAIRY: 20